---
- name: Install chrony configuration file
  template:
    src: chrony.conf.j2
    dest: "{{ chrony_config_file_location }}"
    owner: root
    group: root
    mode: 0644
  register: chrony_config
  notify: Restart chronyd

- name: Ensure chronyd is running
  service:
    enabled: true
    name: chronyd
    state: started

- name: Force chronyd restart
  service:
    name: chronyd
    state: restarted