# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = [
    {
        :name => "k8s-control-plane",
        :type => "master",
        :box => "ubuntu/focal64",
        :box_version => "20211026.0.0 ",
        :eth1 => "192.168.33.10",
        :memory => "2048",
        :cpu => "2",
    },
    {
        :name => "k8s-node-1",
        :type => "node",
        :box => "ubuntu/focal64",
        :box_version => "20211026.0.0 ",
        :eth1 => "192.168.33.11",
        :memory => "512",
        :cpu => "1",
    }
]

Vagrant.configure("2") do |config|
  servers.each do |options|    
    config.vm.define options[:name] do |config|
      config.vm.box = options[:box]
      config.vm.box_version = options[:box_version]
      config.vm.hostname = options[:name]
      config.vm.network :private_network, ip: options[:eth1]
      config.vm.provider "virtualbox" do |v|
          v.name = options[:name]
          v.customize ["modifyvm", :id, "--groups", "/Development"]
          v.customize ["modifyvm", :id, "--memory", options[:memory]]
          v.customize ["modifyvm", :id, "--cpus", options[:cpu]]
      end
    end
  end
end
