- include_tasks: config.yaml

- include_tasks: install.yaml

- name: Ensure containerd config directory exists.
  file:
    path: /etc/containerd
    state: directory
  register: containerd_dir

- name: Get defaults from containerd.
  command: containerd config default
  register: containerd_config_default

- name: Write defaults to config.toml.
  copy:
    dest: /etc/containerd/config.toml
    content: "{{ containerd_config_default.stdout }}"
  notify: restart containerd